/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live View
         * @description Same view model, computed from a real Triage core instead of a mock file.
         */
        get: operations["live_view_api_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenarios */
        get: operations["scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenario */
        get: operations["scenario_api_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scenario Raw
         * @description The mock Triage responses behind a scenario, exactly as the engine receives them.
         */
        get: operations["scenario_raw_api_scenarios__scenario_id__raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DarkRow */
        DarkRow: {
            /** Name */
            name: string;
            /** Silentfor */
            silentFor: string;
        };
        /** Decision */
        Decision: {
            /** Action */
            action: string;
            /** Dimnote */
            dimNote?: string | null;
            /** Dimmed */
            dimmed: boolean;
            /**
             * Level
             * @enum {string}
             */
            level: "good" | "warn" | "bad" | "muted";
            /** Reason */
            reason: string;
            /** Rules */
            rules: components["schemas"]["Rule"][];
            /** Trigger */
            trigger: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "all_clear" | "schedule" | "act_now" | "blind";
            /** Word */
            word: string;
        };
        /** Drill */
        Drill: {
            /** Dark */
            dark?: components["schemas"]["DarkRow"][] | null;
            /** Facts */
            facts: components["schemas"]["Fact"][];
            /** Handled */
            handled?: components["schemas"]["Handled"][] | null;
            /** Note */
            note?: string | null;
            /** Pressure */
            pressure?: components["schemas"]["PressureRow"][] | null;
            /** Services */
            services?: components["schemas"]["ServiceRow"][] | null;
            /** Signals */
            signals?: components["schemas"]["SignalCount"][] | null;
            /** Sparkline */
            sparkline?: number[] | null;
            /** Steps */
            steps?: components["schemas"]["Step"][] | null;
        };
        /** Fact */
        Fact: {
            /** Hint */
            hint?: string | null;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Handled */
        Handled: {
            /** At */
            at: string;
            /** Rca */
            rca?: string | null;
            /** Service */
            service: string;
            /** Title */
            title: string;
        };
        /** Health */
        Health: {
            /** Live */
            live: boolean;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** Indicator */
        Indicator: {
            /** Caption */
            caption: string;
            /** Decides */
            decides: boolean;
            drill?: components["schemas"]["Drill"] | null;
            /** Horizon */
            horizon: string;
            /** How */
            how: string;
            /**
             * Id
             * @enum {string}
             */
            id: "users" | "forecast" | "trust" | "day";
            /** Label */
            label: string;
            /**
             * Level
             * @enum {string}
             */
            level: "good" | "warn" | "bad" | "muted";
            /** Question */
            question: string;
            /** Ring */
            ring: number;
            /** State */
            state: string;
            /** Title */
            title: string;
        };
        /** Outcome */
        Outcome: {
            /** Reason */
            reason?: string | null;
            /** States */
            states: {
                [key: string]: string;
            };
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "all_clear" | "schedule" | "act_now" | "blind";
        };
        /** PressureRow */
        PressureRow: {
            /** Cpustallpct */
            cpuStallPct?: number | null;
            /** Iostallpct */
            ioStallPct?: number | null;
            /** Memofrequestpct */
            memOfRequestPct?: number | null;
            /** Memstallpct */
            memStallPct?: number | null;
            /** Oomkills */
            oomKills: number;
            /** Service */
            service: string;
        };
        /** QueueItem */
        QueueItem: {
            /** Id */
            id: string;
            /** Impact */
            impact: string;
            /** Openfor */
            openFor: string;
            /** Plan */
            plan: string[];
            /** Rca */
            rca?: string | null;
            /** Related */
            related: string[];
            /** Service */
            service: string;
            /** Severity */
            severity: string;
            /** Title */
            title: string;
        };
        /** Rule */
        Rule: {
            /** Fired */
            fired: boolean;
            /** Id */
            id: string;
            /** Leadsto */
            leadsTo: string;
            /** Text */
            text: string;
        };
        /** Scenario */
        Scenario: {
            /** Id */
            id: string;
            /** Story */
            story: string;
            /** Title */
            title: string;
        };
        /** ScenarioListItem */
        ScenarioListItem: {
            /**
             * Actual
             * @enum {string}
             */
            actual: "all_clear" | "schedule" | "act_now" | "blind";
            /**
             * Expected
             * @enum {string}
             */
            expected: "all_clear" | "schedule" | "act_now" | "blind";
            /** File */
            file: string;
            /** Id */
            id: string;
            /** Passed */
            passed: boolean;
            /** Title */
            title: string;
        };
        /** ServiceRow */
        ServiceRow: {
            /** Errpct */
            errPct: number;
            /**
             * Flag
             * @enum {string}
             */
            flag: "good" | "warn" | "bad" | "muted";
            /** Fresh */
            fresh: boolean;
            /** Hitsnext */
            hitsNext: string[];
            /** P99Ms */
            p99Ms?: number | null;
            /** Ready */
            ready: boolean;
            /** Reqpersec */
            reqPerSec: number;
            /** Service */
            service: string;
            /** Tier */
            tier?: number | null;
        };
        /** SignalCount */
        SignalCount: {
            /** Count */
            count: number;
            /** Label */
            label: string;
        };
        /** Source */
        Source: {
            /** Age */
            age: string;
            /** Cluster */
            cluster?: string | null;
            /** Connected */
            connected: boolean;
            /** Label */
            label: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "demo" | "live";
            /** Now */
            now: string;
            /** Tenant */
            tenant: string;
        };
        /** Step */
        Step: {
            /** Done */
            done: boolean;
            /** Text */
            text: string;
        };
        /** Validation */
        Validation: {
            computed: components["schemas"]["Outcome"];
            expected: components["schemas"]["Outcome"];
            /** Passed */
            passed: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** View */
        View: {
            decision: components["schemas"]["Decision"];
            /** Indicators */
            indicators: components["schemas"]["Indicator"][];
            /** Queue */
            queue: components["schemas"]["QueueItem"][];
            scenario?: components["schemas"]["Scenario"] | null;
            source: components["schemas"]["Source"];
            validation?: components["schemas"]["Validation"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    live_view_api_live_get: {
        parameters: {
            query?: {
                tenant?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioListItem"][];
                };
            };
        };
    };
    scenario_api_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_raw_api_scenarios__scenario_id__raw_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
